import {
  generate,
  validateGenerateInput,
  type ArgsFileLoadResult,
  type ConfigData,
  type ConfigFileData,
  type GenerateInput,
  type GenerateSuccess,
  type ProfileData,
  type ProfileFileData,
  type ValidationError,
} from '@launch-composer/core';
import * as vscode from 'vscode';

import type {
  ComposerDataIssue,
  GenerateDiagnostic,
  GenerateReadiness,
} from '../messages.js';
import type { DataFileIo } from '../io/dataFileIo.js';
import { parseJsonc, stringifyJsonFile } from '../io/json.js';
import type { WorkspaceLayout } from '../io/workspaceLayout.js';
import type {
  WorkspaceDataWithoutReadiness,
  WorkspaceReader,
} from '../io/workspaceReader.js';

export interface WorkspaceDataSnapshot {
  profiles: ProfileFileData[];
  configs: ConfigFileData[];
  issues: ComposerDataIssue[];
  generateReadiness: GenerateReadiness;
}

export type WorkspaceGenerateResult =
  | GenerateSuccess
  | {
      success: false;
      issueCount: number;
    };

export class LaunchJsonService {
  constructor(
    private readonly layout: WorkspaceLayout,
    private readonly io: DataFileIo,
    private readonly reader: WorkspaceReader,
  ) {}

  async withGenerateReadiness(
    snapshot: WorkspaceDataWithoutReadiness,
  ): Promise<WorkspaceDataSnapshot> {
    return {
      ...snapshot,
      generateReadiness: await this.getGenerateReadiness(snapshot),
    };
  }

  async generateLaunchJson(): Promise<WorkspaceGenerateResult> {
    const snapshot = await this.withGenerateReadiness(
      await this.reader.readAllData(),
    );
    const readiness = snapshot.generateReadiness;
    if (readiness.diagnostics.length > 0) {
      return {
        success: false,
        issueCount: readiness.diagnostics.length,
      };
    }

    const result = await generate(this.createGenerateInput(snapshot));
    if (!result.success) {
      return {
        success: false,
        issueCount: result.errors.length,
      };
    }

    return result;
  }

  async writeLaunchJson(result: GenerateSuccess): Promise<void> {
    const content =
      '// This file is auto-generated by Launch Composer.\n' +
      '// Do not edit manually. Changes will be overwritten.\n' +
      stringifyJsonFile(result.launchJson);

    await this.io.createDirectory(
      vscode.Uri.joinPath(this.layout.workspaceRoot, '.vscode'),
    );
    await this.io.writeTextFile(this.layout.getLaunchJsonUri(), content);
  }

  async launchJsonExists(): Promise<boolean> {
    return this.io.exists(this.layout.getLaunchJsonUri());
  }

  private async getGenerateReadiness(
    snapshot: WorkspaceDataWithoutReadiness,
  ): Promise<GenerateReadiness> {
    if (snapshot.issues.length > 0) {
      return {
        diagnostics: snapshot.issues.map((issue) =>
          createInvalidFileDiagnostic(issue),
        ),
      };
    }

    const errors = await validateGenerateInput(
      this.createGenerateInput(snapshot),
    );

    return {
      diagnostics: errors.map((error) =>
        createCoreValidationDiagnostic(error, snapshot),
      ),
    };
  }

  private createGenerateInput(
    snapshot: Pick<WorkspaceDataSnapshot, 'profiles' | 'configs'>,
  ): GenerateInput {
    return {
      profiles: snapshot.profiles,
      configs: snapshot.configs,
      variables: {
        workspaceFolder: this.layout.getWorkspaceRootPath(),
      },
      readArgsFile: (resolvedPath) => this.readArgsFile(resolvedPath),
    };
  }

  private async readArgsFile(
    resolvedPath: string,
  ): Promise<ArgsFileLoadResult> {
    try {
      const result = await this.io.readTextFile(vscode.Uri.file(resolvedPath));
      if (result.status === 'missing') {
        return { kind: 'not-found' };
      }

      const value = parseJsonc<unknown>(result.text, resolvedPath);
      return { kind: 'success', data: value };
    } catch (error) {
      return {
        kind: 'error',
        message:
          error instanceof Error ? error.message : 'Failed to read argsFile.',
      };
    }
  }
}

function createInvalidFileDiagnostic(
  issue: ComposerDataIssue,
): GenerateDiagnostic {
  return {
    source: 'invalid-file',
    file: issue.file,
    message: issue.message,
    target: { kind: 'file' },
  };
}

function createCoreValidationDiagnostic(
  error: ValidationError,
  snapshot: WorkspaceDataWithoutReadiness,
): GenerateDiagnostic {
  if (error.target.kind === 'profile') {
    const profile = findProfileEntry(
      snapshot.profiles,
      error.file,
      error.target.index,
    );
    const target: GenerateDiagnostic['target'] = {
      kind: 'profile',
    };
    if (error.target.index !== undefined) {
      target.index = error.target.index;
    }
    if (profile?.name !== undefined) {
      target.name = profile.name;
    }
    if (error.field !== undefined) {
      target.field = error.field;
    }
    return {
      source: 'core-validation',
      file: error.file,
      message: error.message,
      target,
    };
  }

  if (error.target.kind === 'config') {
    const config = findConfigEntry(
      snapshot.configs,
      error.file,
      error.target.index,
    );
    const target: GenerateDiagnostic['target'] = {
      kind: 'config',
    };
    if (error.target.index !== undefined) {
      target.index = error.target.index;
    }
    const name = config?.data.name ?? error.configName;
    if (name !== undefined) {
      target.name = name;
    }
    if (error.field !== undefined) {
      target.field = error.field;
    }
    return {
      source: 'core-validation',
      file: error.file,
      message: error.message,
      target,
    };
  }

  const target: GenerateDiagnostic['target'] = {
    kind: 'file',
  };
  if (error.field !== undefined) {
    target.field = error.field;
  }

  return {
    source: 'core-validation',
    file: error.file,
    message: error.message,
    target,
  };
}

function findProfileEntry(
  files: ProfileFileData[],
  file: string,
  index: number | undefined,
): ProfileData | undefined {
  if (index === undefined) {
    return undefined;
  }

  return files.find((fileData) => fileData.file === file)?.profiles[index];
}

function findConfigEntry(
  files: ConfigFileData[],
  file: string,
  index: number | undefined,
): { index: number; data: ConfigData } | undefined {
  if (index === undefined) {
    return undefined;
  }

  const data = files.find((fileData) => fileData.file === file)?.configurations[
    index
  ];
  return data === undefined ? undefined : { index, data };
}
